name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main ## 이 브랜치를 통해 커밋되면 자동으로 배포된다.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest ## 실행할 OS

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 ## 최신버전의 소스코드 가져옴

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Zip Artifact for Deployment
        run: zip -r deploy.zip . ## 현재 위치에서 압축해서 deploy.zip 파일을 생성
      
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: | ## 밑에 있는 명령들 순서대로 실행하겠다.
         aws configure set region $AWS_REGION
         aws s3 cp deploy.zip s3://netflix-bucket/deploy.zip 
      
      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "nestjs-netflix" \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket="netflix-bucket",S3Key="deploy.zip"
          
          aws elasticbeanstalk update-environment \
            --application-name "nestjs-netflix" \
            --environment-name "Nestjs-netflix-env" \
            --version-label $GITHUB_SHA
